apiVersion: v1
kind: Service
metadata:
  name: {{ include "r2-broker.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "r2-broker.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "r2-broker.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
