{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cloudflared
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: cloudflared
    app.kubernetes.io/component: tunnel
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudflared
      app.kubernetes.io/component: tunnel
{{- end }}
